#!/bin/bash

NS4U=${0%/*}/nosqoop4u.rb
CLASSPATH=$CLASSPATH:$HOME/jars/mysql-connector-java-5.1.15-bin.jar
CLASSPATH=$CLASSPATH:$HOME/jars/postgresql-9.0-801.jdbc4.jar
CLASSPATH=$CLASSPATH:$HOME/jars/ojdbc14_v10.2.0.4.jar
export CLASSPATH
JRUBY_OPTS=

if ! type -p jruby >&/dev/null; then
  echo error: cannot find jruby...please set your PATH >&2
  exit 1
fi

if [ ! -f $NS4U ]; then
  echo error: cannot find nosqoop4u.rb...please install it alongside: >&2
  echo "       $0" >&2
  exit 1
fi

exec jruby $JRUBY_OPTS $NS4U "$@"
